# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sam-bot"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-126oc7da84yev"
s3_prefix = "sam-bot"
region = "us-east-2"
image_repositories = ["HelloWorldFunction=492604706822.dkr.ecr.us-east-2.amazonaws.com/sambot9385960c/helloworldfunction19d43fc4repo"]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
